### ISSUE TITLE
error in workflow

### ISSUE THREAD

**Issue by cuiwang** [liszd/whyliam.workflows.youdao#14]
no json object could be decoded

**Comment by liszd** [comment]
我暂时不知道导致这个错误的原因，你先这么处理

删除
```
/Users/用户名/Library/Application Support/Alfred 2/Workflow Data/com.whyliam.workflows.youdao/
```

**Comment by touchmii** [comment]
选择有道发音没有效果，如按住shift就可以用了，怎么解决？

**Comment by liszd** [comment]
@touchmii 

1. 按回车 复制
2. 按Control+回车 打开有道翻译页面
3. 按Command+回车 直接在打出翻译结果
4. 按Shift+回车 直接发音

**Comment by SendSonS** [comment]
/Users/用户名/Library/Application Support/Alfred 2/Workflow Data/com.whyliam.workflows.youdao/
/Users/用户名/Library/Application Support/Alfred 3/Workflow Data/com.whyliam.workflows.youdao/
下面的
settings.json
不是json格式，解析失败
要么删除这个文件，要么打开这个文件输入一个空的json串：
{}
然后保存退出。

我看其他的workflow的这个设置文件是有内容的，不清楚这个是在哪里设置的？

**Comment by liszd** [comment]
@SendSonS 这个文件是 插件的版本
```
{
  "__workflow_last_version": "1.1.0"
}
```
是自动生成的，我暂时找不到解决方法

**Comment by SendSonS** [comment]
是的，其他插件里是保存的版本信息，但是你的这个插件里是空的，什么都没有，不知道是不是哪里触发了什么，把这个文件重置了？

**Comment by liszd** [comment]
@SendSonS 我发现版本id写错了，使用最新版本后应该可以解决这个问题。
（建议先删掉老版本）
谢谢了
