### ISSUE TITLE
按回车复制、按Command+回车复制，输出的复制结果是一样的。

### ISSUE THREAD

**Issue by onestark** [liszd/whyliam.workflows.youdao#15]
按回车复制的列出的翻译结果条目，但是按 ⌘+回车 复制，输出的复制结果也是和前者一样。
给 **splitargs.py** 的 `def getargs(wf)` 添加一个 else 条件：

```python
def getargs(wf):
    # .....
    if part == 1:
        # .....
    elif part == 2:
        # .....
    else:
        sys.stdout.write(query[2].strip())
    return 0
```

然后在 workflow 的 cmd 脚本中修改为非 1 和 2，我改为 3：`/usr/bin/python splitargs.py "{query}" 3`

才能 ⌘+回车 直接复制输入的 `{query}`。

**Comment by liszd** [comment]
`回车` 是复制
`⌘+回车` 是打印翻译结果
