### ISSUE TITLE
昨天起无法使用了，报错如图

### ISSUE THREAD

**Issue by fenbox** [liszd/whyliam.workflows.youdao#17]
![image](https://cloud.githubusercontent.com/assets/360618/16402754/627f8778-3d21-11e6-8499-d0e94b3fe203.png)

**Comment by liszd** [comment]
我昨天原来代码的发现了一个问题，但是不确定是不是这个问题导致的。
请删掉原来的workflows，再下载最新版本重新安装
麻烦反馈一下结果，谢谢。

**Comment by fenbox** [comment]
可以了，可以正常翻译了，感谢 ^___^
