### ISSUE TITLE
Help! 前一秒钟还是好使的， 不是key的问题...

### ISSUE THREAD

**Issue by codezm** [liszd/whyliam.workflows.youdao#19]
![qq20160713-0](https://cloud.githubusercontent.com/assets/12092275/16805774/590a4064-4944-11e6-9b12-d8218024c032.png)

**Comment by codezm** [comment]
这样可以吗？

**Comment by liszd** [comment]
我之前代码出了个比较严重的问题。请删掉老版本下载新版本
[https://github.com/liszd/whyliam.workflows.youdao/releases](https://github.com/liszd/whyliam.workflows.youdao/releases)

**Comment by codezm** [comment]
还是不好使， 我重新安装还是失败的～  电脑重启也是失败的

**Comment by liszd** [comment]
### 方法一

在 `/Users/用户名/Library/Application\ Support/Alfred\ 2/Workflow\ Data/whyliam.workflows.youdao` 中新建`settings.json`文件，内容是

```
{
  "__workflow_last_version": "1.2.3"
}
```

### 方法二
直接删除
`/Users/用户名/Library/Application\ Support/Alfred\ 2/Workflow\ Data/whyliam.workflows.youdao`

**Comment by codezm** [comment]
搞定！ 多谢!
