### ISSUE TITLE
这几天又不能用了：no json object could be decoded

### ISSUE THREAD

**Issue by fenbox** [liszd/whyliam.workflows.youdao#21]
![image](https://cloud.githubusercontent.com/assets/360618/18414992/b1d0a30c-7813-11e6-87b7-794a7230bd9d.png)

**Comment by liszd** [comment]
如果出现`No JSON object could be decoded`

![No JSON object could be decoded](https://cloud.githubusercontent.com/assets/12092275/16805774/590a4064-4944-11e6-9b12-d8218024c032.png)

请删除该文件
`/Users/用户名/Library/Application\ Support/Alfred\ 2/Workflow\ Data/whyliam.workflows.youdao`

**Comment by fenbox** [comment]
删掉后恢复正常了 ^_^
