### ISSUE TITLE
查询次数太多

### ISSUE THREAD

**Issue by lisanhu** [liszd/whyliam.workflows.youdao#22]
## 问题描述
非常好用的插件，但是由于alfred每次键入字母的时候都会启动一个查询，而有道查询API反应并不是很迅速，导致查询结果显示非常慢

希望能够在键入全部查询文本后再进行查询

## 改进建议
- 在Script Filter，语言那一行中有一个运行行为(run behaviour)，在这里可以设置
	* 调度模式(queue mode)
		- 上一脚本结束后执行(FIFO，默认)
		- 终止上次查询：效果会很好，但是可能会在短时间内创建关闭很多次socket
	* 延时调度(queue delay)
		- 每字母后立刻执行(默认)
		- 默认延时(用来等待用户停止输入)
		- 订制延时

- 在`youdao.py`脚本中我增加了两行用于判断最后一个字母是否是空格，如果是则执行查询，否则结束脚本，我用空格作为查询结束符
	* 使用这种方式不用让用户等待延时，也不会创建太多的socket
	* 缺点是需要通知用户查询必须以空格结尾，否则无法正常查询

非常感谢你们做了这么好的插件

**Comment by liszd** [comment]
使用空格结尾确实有点不太人性  
我使用了 automatic delay 希望可以缓解一点。

**Comment by lisanhu** [comment]
确实好了不少
而且用空格结尾感觉还是有点慢，解释器启动的原因？

automatic delay挺好用的，虽然还是有多次查询，但是起码现在感觉反应还挺快的
