### ISSUE TITLE
no JSON object could be decoded 

### ISSUE THREAD

**Issue by Molarace** [liszd/whyliam.workflows.youdao#25]
for some reason Couchpotato could not snatch movies form Torrentday below is the log

[edia._base.providers.base] Failed to parsing TorrentDay: Traceback (most recent call last): File "/share/CACHEDEV1_DATA/.qpkg/CouchPotato2/CouchPotato2/couchpotato/core/media/_base/providers/base.py", line 84, in getJsonData return json.loads(data) File "/share/CACHEDEV1_DATA/.qpkg/Python/lib/python2.7/json/__init__.py", line 338, in loads return _default_decoder.decode(s) File "/share/CACHEDEV1_DATA/.qpkg/Python/lib/python2.7/json/decoder.py", line 366, in decode obj, end = self.raw_decode(s, idx=_w(s, 0).end()) File "/share/CACHEDEV1_DATA/.qpkg/Python/lib/python2.7/json/decoder.py", line 384, in raw_decode raise ValueError("No JSON object could be decoded") ValueError: No JSON object could be decoded

**Comment by liszd** [comment]
I think you should submit the Issues to Couchpotato.

**Comment by Molarace** [comment]
thank you appreciate your kind effort.
