### ISSUE TITLE
队长 不能用了！

### ISSUE THREAD

**Issue by kenneth-hao** [liszd/whyliam.workflows.youdao#28]
队长 不能用了！

**Comment by liszd** [comment]
有提示什么错误吗，我这还是可以的

**Comment by follyxing** [comment]
@liszd 应该是有道API更改了。更新下吧。不能用了。

**Comment by liszd** [comment]
@follyxing 你更新一下试一试，因为我这还可以使用，暂时没有发现

**Comment by kenneth-hao** [comment]
我重新装了下，又好了。。 一脸懵逼。。  应该是不小心动了个人配置
谢谢队长 ~
