### ISSUE TITLE
No JSON object could be decoded

### ISSUE THREAD

**Issue by chuangker** [liszd/whyliam.workflows.youdao#30]
突然用不了
尝试删除 whyliam.workflows.youdao 之后 
还是提示 No JSON object could be decoded

试着删除重新安装，还是一样的问题

**Comment by graycarl** [comment]
我也是同样的问题

**Comment by kenneth-hao** [comment]
查看工具源码后发现工具会使用有道翻译的接口
eg. 
http://fanyi.youdao.com/openapi.do?keyfrom=whyliam&key=1331254833&type=data&doctype=json&version=1.1&q=hello

往往是由于同一个 app 账号接口调用次数过多导致，超过1000 times/day.
去官网 http://fanyi.youdao.com/openapi?path=data-mode
申请自己的 AppID  修改源码文件 youdao.py 即可

**Comment by chuangker** [comment]
@kenneth-hao 果然是这样，不过提示不友好啊。
thx，解决了！

**Comment by liszd** [comment]
没想到现在用的人挺多的，我现在加了10个Key。你们可以更新一下

**Comment by kenneth-hao** [comment]
居然了申请了这么多账号。。 作者辛苦了。。
