### ISSUE TITLE
No json objectr could be decoeded

### ISSUE THREAD

**Issue by Bovey0809** [liszd/whyliam.workflows.youdao#35]
删除了文件还是不行

**Comment by liszd** [comment]
@Bovey0809 是这样的
现在导致这个问题的原因有两个，
一个是文件生成错误导致，
一个是youdao的key的次数被用完了导致的。

如果现在可以用了，那就是key被用完的可能比较大，
建议先更新到最新版，最新版增加了很多key，
如果问题的没有解决，建议可以是自己申请一个key来修改。

我最近在出差，下一版本可以自定义key。

**Comment by Bovey0809** [comment]
好的，谢谢回复啦，等你更新

**Comment by liszd** [comment]
先使用最新版，最新版应该还是可以支持一段时间的。

**Comment by Bovey0809** [comment]
はい。ありがとうございます。
