### ISSUE TITLE
某种情况下会导致cpu使用率100%

### ISSUE THREAD

**Issue by xlvecle** [liszd/whyliam.workflows.youdao#37]
![image](https://cloud.githubusercontent.com/assets/8241747/24688373/27e4a680-19f2-11e7-948e-f287a7865b14.png)
![image](https://cloud.githubusercontent.com/assets/8241747/24688389/38fb273c-19f2-11e7-8c0a-067abcbcc7b9.png)

**Comment by liszd** [comment]
好像是更新程序有问题，我看一下

**Comment by JasinYip** [comment]
这个问题解决了吗？我这里依然存在这个问题。

不知道这个链接是否有帮助：https://github.com/deanishe/alfred-workflow/issues/111

**Comment by liszd** [comment]
@JasinYip 程序更新最新版了吗？最新版本我取消了自动更新，改成了手动更新。
你给的链接很有帮助，计划下个版本更新一下。
谢谢
