### ISSUE TITLE
一个python进程占用的问题

### ISSUE THREAD

**Issue by fanglei-hangzhou** [liszd/whyliam.workflows.youdao#40]
偶尔会导致后台一个python进程长期占用cpu99%。导致系统发热。

**Comment by liszd** [comment]
谢谢，已经收到相关反馈。
下个版本将处理这个问题。

**Comment by JasinYip** [comment]
请问有进度了吗？天天 100% 呢 T_T

**Comment by liszd** [comment]
@fanglei-hangzhou @JasinYip 我更新了workflow， 你们可以试一下 [v2.0.1](https://github.com/liszd/whyliam.workflows.youdao/releases/tag/2.0.1)

cpu还是过高的话继续和留言
