### ISSUE TITLE
有道API已经更新了.

### ISSUE THREAD

**Issue by steventong** [liszd/whyliam.workflows.youdao#41]
请求URL已经有所变更,,目前不能申请到老式的key了.新的key在目前的api url里面无法使用的

**Comment by Kaijun** [comment]
是的 现在推出了有道云服务。。。
http://ai.youdao.com/docs/api.s

**Comment by Kaijun** [comment]
@steventong 如果你和我一样使用新的接口，可以先尝试使用我修改后的版本：https://github.com/Kaijun/whyliam.workflows.youdao

**Comment by liszd** [comment]
之前考虑过这个问题，新的有道云服务的key不太适合公共使用，可能还是需要兼容一下之前的老版。

@steventong 你可以先用一下 @Kaijun 的版本。

谢谢 @Kaijun

**Comment by Kaijun** [comment]
@liszd 是这样的。而且新的 api 看起来是要收费了，虽然目前有免费100元代金试用。
但是目前老的接口经常会查询失败

**Comment by liszd** [comment]
@Kaijun 新的api有一个免费额度，个人使用基本够用。

老接口失败的原因是使用的人太多了，老接口有一个每小时的上限。

**Comment by liszd** [comment]
刚刚发现youdao `自然语言翻译服务每日10万免费字符暂停提供`。

看来免费的服务没了

**Comment by steventong** [comment]
@Kaijun    哈哈 。多谢 。不知道可以考虑做一个Google 翻译服务，Google翻译已经不墙了。

**Comment by zhanggang807** [comment]
@Kaijun 有可以下载的吗？

**Comment by zebrallel** [comment]
辛亏对文本翻译的需求不大，新的API不支持就算啦 :)

**Comment by liszd** [comment]
@zebrallel 已经准备开发新的翻译模式了，不过翻译效果远没有现在的好。

**Comment by Kaijun** [comment]
@zhanggang807 直接下载我 repo 就行了 然后在 alfred 导入

**Comment by Kaijun** [comment]
@zhanggang807 不好意思 注意是 develop 分支 https://github.com/Kaijun/whyliam.workflows.youdao/tree/develop

**Comment by yisshengyouni** [comment]
我自己申请了一个，但查询经常会出现301，大家有解决方法吗
