### ISSUE TITLE
重启电脑后,有道不能翻译了

### ISSUE THREAD

**Issue by qiusong2613** [liszd/whyliam.workflows.youdao#46]
![default](https://user-images.githubusercontent.com/24889186/29706979-3be1447a-89b6-11e7-839d-9dbb05ac1b3b.png)

**Comment by liszd** [comment]
你好，请问你使用的是最新版本吗？[有道翻译](https://github.com/liszd/whyliam.workflows.youdao/releases) 下载 v2.1.0
