### ISSUE TITLE
可否考虑添加自动发音和查词历史功能

### ISSUE THREAD

**Issue by Xwoder** [liszd/whyliam.workflows.youdao#51]
可否考虑使用热键查词时，也就是诸如双击 Option 查询已选中单词，添加自动发音功能。

另外的，可否增加一个查看查词历史的功能，方便用户将将最近的单词查询记录导出至特定位置，或者直接将查询历史保存到用户指定文件中。

谢谢，这个查单词 workflow 真的很好用

**Comment by liszd** [comment]
@Xwoder 自动发音，应该不会添加，毕竟还是比较小众的需求。

我有空加一下查词历史😄

**Comment by liszd** [comment]
`yd *`
