### ISSUE TITLE
添加了有道智云API,依然提示有道翻译使用频率高

### ISSUE THREAD

**Issue by JavanTang** [liszd/whyliam.workflows.youdao#53]
RT

**Comment by liszd** [comment]
![](https://ws2.sinaimg.cn/large/006tKfTcgy1fiosfttuejj31kw0vb493.jpg)

请检查一下是否在 ziyun_id, ziyun_key 中填入了相关的id, key.

**Comment by miltonleex** [comment]
同样的情况，删除workflow后，重新安装就好了
