### ISSUE TITLE
同步到单词本出错了

### ISSUE THREAD

**Issue by Lillls** [liszd/whyliam.workflows.youdao#60]
同步到单词本出错了  [ERROR: action.script] .

**Comment by jokefaker** [comment]
我也有这个问题，账号密码都是对的

**Comment by MuYunyun** [comment]
首先必须是网易邮箱登入，另外补充一个 app —— 有道背单词，单词同步到网易有道词典的同时，也会同步到这上面来。我这边使用良好，如果还有错误，请把复现一下操作步骤。

**Comment by xiebruce** [comment]
我试了没问题，不成功的童鞋，是不是自己添加错地方了？要双击这个：
<img width="972" alt="xnip2018-09-11_13-52-56" src="https://user-images.githubusercontent.com/13575500/45340676-0ebba580-b5ca-11e8-8ffd-6861735f29d7.png">
把里面的 `yourname` 替换为你的网易账号邮箱，`yoursecret` 替换为你的网易账号的密码

**Comment by MuYunyun** [comment]
@liszd 没问题的话，这个 issue 可以关闭了

**Comment by jokefaker** [comment]
这里我知道原因了，我用 手机号@163.com 是可以直接在有道词典登录的，可能这个API不支持，需要输入登录后显示的邮箱。可以关掉了，多谢各位反馈。
