### ISSUE TITLE
有道查询api返回有变动,导致返回结果解释报错

### ISSUE THREAD

**Issue by kevin-lucifer** [liszd/whyliam.workflows.youdao#65]
日志如下,有空看看
[2019-01-30 17:13:17][ERROR: input.scriptfilter] Code 1: .
17:13:17 workflow.py:2055 DEBUG    ---------- Youdao (2.2.0) ----------
17:13:17 workflow.py:1462 DEBUG    reading settings from /Users/xxx/Library/Application Support/Alfred 3/Workflow Data/whyliam.workflows.youdao/settings.json
17:13:17 workflow.py:2339 DEBUG    update check not due
17:13:17 workflow.py:2074 ERROR    'NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "/Users/xxx/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.xxx/workflow/workflow.py", line 2067, in run
    func(self)
  File "youdao.py", line 250, in main
    get_phonetic(query, isEnglish, rt)
  File "youdao.py", line 173, in get_phonetic
    if rt["basic"].get("phonetic"):
AttributeError: 'NoneType' object has no attribute 'get'
17:13:17 workflow.py:2097 DEBUG    ---------- finished in 0.183s ----------

**Comment by kevin-lucifer** [comment]
改了下,有需要的同学自己加上
`        elif errorCode == "0":
            isEnglish = check_English(query)
            if rt.get("basic"):
                get_phonetic(query, isEnglish, rt)
                get_explains(query, isEnglish, rt)
            get_translation(query, isEnglish, rt)
            get_web_translation(query, isEnglish, rt)`

**Comment by dxvgef** [comment]
我最近也是频繁出错，但再试几次又好了

**Comment by dxvgef** [comment]
> 改了下,有需要的同学自己加上
> ``
> elif errorCode == "0":
> isEnglish = check_English(query)
> if rt.get("basic"):
> get_phonetic(query, isEnglish, rt)
> get_explains(query, isEnglish, rt)
> get_translation(query, isEnglish, rt)
> get_web_translation(query, isEnglish, rt)
> ''

请问具体是改哪个文件？

**Comment by liszd** [comment]
你们使用的是`有道翻译旧的key` 还是 `有道智云的key`？

**Comment by dxvgef** [comment]
> 你们使用的是`有道翻译旧的key` 还是 `有道智云的key`？

智云的

**Comment by liszd** [comment]
接口确实变了，我修改一下

**Comment by liszd** [comment]
更新了 https://github.com/liszd/whyliam.workflows.youdao/releases

**Comment by dxvgef** [comment]
感谢！！！
