### ISSUE TITLE
Feature Request: 自动更新

### ISSUE THREAD

**Issue by Voleking** [liszd/whyliam.workflows.youdao#69]
感谢插件，可否考虑加上自动更新功能，像这个一样[alfred-safari-assistant](https://github.com/deanishe/alfred-safari-assistant)

**Comment by liszd** [comment]
@Voleking 开发版本已经有自动更新的功能，等把其他的问题都处理后，在发个版本吧 https://github.com/liszd/whyliam.workflows.youdao/tree/develop
